version: '3.8'

services:
  user-app:
    build:
      context: .
      dockerfile: Dockerfile.user
    ports:
      - "80:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    volumes:
      - .:/app
    networks:
      - app-network

  admin-app:
    build:
      context: .
      dockerfile: Dockerfile.admin
    ports:
      - "8502:8502"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge